import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import LocalFont from 'next/font/local'
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const calSans = LocalFont({
  src: "../public/fonts/CalSans-SemiBold.ttf",
  variable: "--font-calsans",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black ${inter.variable} ${calSans.variable} ${process.env.NODE_ENV === "development" ? "debug-screens" : undefined} antialiased font-inter`}
      >
        {children}
      </body>
    </html>
  );
}
