/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SeoOpenGraph = {
  url?: string;
  title?: string;
  description?: string;
  siteName?: string;
  type?:
    | "website"
    | "article"
    | "profile"
    | "book"
    | "music"
    | "video"
    | "product";
  imageType?: "upload" | "url";
  image?: OpenGraphImage;
  imageUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type OpenGraphImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "openGraph.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type SeoTwitter = {
  card?: "summary" | "summary_large_image" | "app" | "player";
  site?: string;
  creator?: string;
  title?: string;
  description?: string;
  imageType?: "upload" | "url";
  image?: TwitterImage;
  imageUrl?: string;
};

export type TwitterImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "twitter.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type SettingsProjects = {
  _id: string;
  _type: "settingsProjects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoFields;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type SeoFields = {
  _type: "seoFields";
  robots?: Robots;
  title?: string;
  description?: string;
  metaImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  metaAttributes?: Array<
    {
      _key: string;
    } & MetaAttribute
  >;
  keywords?: Array<string>;
  canonicalUrl?: string;
  openGraph?: SeoOpenGraph;
  twitter?: SeoTwitter;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  forcedRobots?: {
    index?: boolean;
    follow?: boolean;
  };
  seo?: SeoFields;
};

export type HorizontalImageGroup = {
  _type: "horizontalImageGroup";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainProject?: boolean;
  visible?: boolean;
  published?: boolean;
  title: string;
  description: string;
  slug: Slug;
  date?: string;
  url?: string;
  repository?: string;
  tags: Array<
    {
      _key: string;
    } & TagReference
  >;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & InlineBadge)
          | ({
              _key: string;
            } & InlineChip)
          | {
              url?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & HorizontalImageGroup)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type InlineBadge = {
  _type: "inlineBadge";
  color?: Color;
  logo?: string;
  logoColor?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type InlineChip = {
  _type: "inlineChip";
  color?:
    | "gray"
    | "blue"
    | "green"
    | "red"
    | "yellow"
    | "purple"
    | "orange"
    | "black"
    | "white";
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type Robots = {
  _type: "robots";
  noIndex?: boolean;
  noFollow?: boolean;
};

export type MetaTag = {
  _type: "metaTag";
  metaAttributes?: Array<
    {
      _key: string;
    } & MetaAttribute
  >;
};

export type MetaAttribute = {
  _type: "metaAttribute";
  key?: string;
  type?: "string" | "image";
  value?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Twitter = {
  _type: "twitter";
  card?: "summary" | "summary_large_image" | "app" | "player";
  site?: string;
  creator?: string;
  title?: string;
  description?: string;
  imageType?: "upload" | "url";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
};

export type OpenGraph = {
  _type: "openGraph";
  url?: string;
  title?: string;
  description?: string;
  siteName?: string;
  type?:
    | "website"
    | "article"
    | "profile"
    | "book"
    | "music"
    | "video"
    | "product";
  imageType?: "upload" | "url";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SeoOpenGraph
  | SanityImageAssetReference
  | OpenGraphImage
  | SeoTwitter
  | TwitterImage
  | ProjectReference
  | SettingsProjects
  | SeoFields
  | Settings
  | HorizontalImageGroup
  | Tag
  | Slug
  | TagReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | InlineBadge
  | Color
  | InlineChip
  | RgbaColor
  | HsvaColor
  | HslaColor
  | Robots
  | MetaTag
  | MetaAttribute
  | Twitter
  | OpenGraph
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  forcedRobots?: {
    index?: boolean;
    follow?: boolean;
  };
  seo?: SeoFields;
} | null;

// Source: sanity/lib/queries.ts
// Variable: projectsPageDataQuery
// Query: {  "featuredIds": *[_type == "settingsProjects"][0].featuredProjects[]._ref,  "projects": *[    _type == "project" &&    visible == true  ] | order(date desc) {    _id,    "slug": slug.current,    title,    description,    date,    mainProject,    "tags": tags[]->{      _id,      title,      "slug": slug.current    }  }}
export type ProjectsPageDataQueryResult = {
  featuredIds: Array<string> | null;
  projects: Array<{
    _id: string;
    slug: string;
    title: string;
    description: string;
    date: string | null;
    mainProject: boolean | null;
    tags: Array<{
      _id: string;
      title: string;
      slug: string;
    }>;
  }>;
};

// Source: sanity/lib/queries.ts
// Variable: projectDataQuery
// Query: *[_type == "project" && slug.current == $slug][0]{  _id,  title,  description,  date,  repository,  url,  "slug": slug.current,  "tags": tags[]->{    _id,    title,    "slug": slug.current  },  "content": content[],}
export type ProjectDataQueryResult = {
  _id: string;
  title: string;
  description: string;
  date: string | null;
  repository: string | null;
  url: string | null;
  slug: string;
  tags: Array<{
    _id: string;
    title: string;
    slug: string;
  }>;
  content: Array<
    | ({
        _key: string;
      } & HorizontalImageGroup)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & InlineBadge)
          | ({
              _key: string;
            } & InlineChip)
          | {
              url?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: getAllProjectSlugsQuery
// Query: *[_type == "project" && defined(slug.current) && visible == true]{  "slug": slug.current}
export type GetAllProjectSlugsQueryResult = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult;
    '{\n  "featuredIds": *[_type == "settingsProjects"][0].featuredProjects[]._ref,\n\n  "projects": *[\n    _type == "project" &&\n    visible == true\n  ] | order(date desc) {\n    _id,\n    "slug": slug.current,\n    title,\n    description,\n    date,\n    mainProject,\n\n    "tags": tags[]->{\n      _id,\n      title,\n      "slug": slug.current\n    }\n  }\n}': ProjectsPageDataQueryResult;
    '*[_type == "project" && slug.current == $slug][0]{\n  _id,\n  title,\n  description,\n  date,\n  repository,\n  url,\n\n  "slug": slug.current,\n\n  "tags": tags[]->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  "content": content[],\n}': ProjectDataQueryResult;
    '*[_type == "project" && defined(slug.current) && visible == true]{\n  "slug": slug.current\n}': GetAllProjectSlugsQueryResult;
  }
}
